journal:[
{events: ["carrot","exercise","weekend"],pulpo:false},
{events: ["bread","pudding","brushed teeth","weekend","touched tree"],pulpo:false},
{events: ["carrot","nachos","brushed teeth","cycling","weekend"],pulpo:false},
{events: ["brussel sprouts","ice cream","brushed teeth","computer","weekend"],pulpo:false},
{events: ["potatoes","candy","brushed teeth","exercise","weekend","dentist"],pulpo:false},
{events: ["brussel sprouts","pudding","brushed teeth","running","weekend"],pulpo:false},
{events: ["pizza","brushed teeth","computer","work","touched tree"],pulpo:false},
{events: ["bread","beer","brushed teeth","cycling","work"],pulpo:false},
{events: ["cauliflower","brushed teeth","work"],pulpo:false},
{events: ["pizza","brushed teeth","cycling","work"],pulpo:false},
{events: ["lasagna","nachos","brushed teeth","work"],pulpo:false},
{events: ["brushed teeth","weekend","touched tree"],pulpo:false},
{events: ["lettuce","brushed teeth","television","weekend"],pulpo:false},
{events: ["spaghetti","brushed teeth","work"],pulpo:false},
{events: ["brushed teeth","computer","work"],pulpo:false},
{events: ["lettuce","nachos","brushed teeth","work"],pulpo:false},
{events: ["carrot","brushed teeth","running","work"],pulpo:false},
{events: ["brushed teeth","work"],pulpo:false},
{events: ["cauliflower","reading","weekend"],pulpo:false},
{events: ["bread","brushed teeth","weekend"],pulpo:false},
{events: ["lasagna","brushed teeth","exercise","work"],pulpo:false},
{events: ["spaghetti","brushed teeth","reading","work"],pulpo:false},
{events: ["carrot","ice cream","brushed teeth","television","work"],pulpo:false},
{events: ["spaghetti","nachos","work"],pulpo:false},
{events: ["cauliflower","ice cream","brushed teeth","cycling","work"],pulpo:false},
{events: ["spaghetti","peanuts","computer","weekend"],pulpo:true},
{events: ["potatoes","ice cream","brushed teeth","computer","weekend"],pulpo:false},
{events: ["potatoes","ice cream","brushed teeth","work"],pulpo:false},
{events: ["peanuts","brushed teeth","running","work"],pulpo:false},
{events: ["potatoes","exercise","work"],pulpo:false},
{events: ["pizza","ice cream","computer","work"],pulpo:false},
{events: ["lasagna","ice cream","work"],pulpo:false},
{events: ["cauliflower","candy","reading","weekend"],pulpo:false},
{events: ["lasagna","nachos","brushed teeth","running","weekend"],pulpo:false},
{events: ["potatoes","brushed teeth","work"],pulpo:false},
{events: ["carrot","work"],pulpo:false},
{events: ["pizza","beer","work","dentist"],pulpo:false},
{events: ["lasagna","pudding","cycling","work"],pulpo:false},
{events: ["spaghetti","brushed teeth","reading","work"],pulpo:false},
{events: ["spaghetti","pudding","television","weekend"],pulpo:false},
{events: ["bread","brushed teeth","exercise","weekend"],pulpo:false},
{events: ["lasagna","peanuts","work"],pulpo:true},
{events: ["pizza","work"],pulpo:false},
{events: ["potatoes","exercise","work"],pulpo:false},
{events: ["brushed teeth","exercise","work"],pulpo:false},
{events: ["spaghetti","brushed teeth","television","work"],pulpo:false},
{events: ["pizza","cycling","weekend"],pulpo:false},
{events: ["carrot","brushed teeth","weekend"],pulpo:false},
{events: ["carrot","beer","brushed teeth","work"],pulpo:false},
{events: ["pizza","peanuts","candy","work"],pulpo:true},
{events: ["carrot","peanuts","brushed teeth","reading","work"],pulpo:false},
{events: ["potatoes","peanuts","brushed teeth","work"],pulpo:false},
{events: ["carrot","nachos","brushed teeth","exercise","work"],pulpo:false},
{events: ["pizza","peanuts","brushed teeth","television","weekend"],pulpo:false},
{events: ["lasagna","brushed teeth","cycling","weekend"],pulpo:false},
{events: ["cauliflower","peanuts","brushed teeth","computer","work","touched tree"],pulpo:false},
{events: ["lettuce","brushed teeth","television","work"],pulpo:false},
{events: ["potatoes","brushed teeth","computer","work"],pulpo:false},
{events: ["bread","candy","work"],pulpo:false},
{events: ["potatoes","nachos","work"],pulpo:false},
{events: ["carrot","pudding","brushed teeth","weekend"],pulpo:false},
{events: ["carrot","brushed teeth","exercise","weekend","touched tree"],pulpo:false},
{events: ["brussel sprouts","running","work"],pulpo:false},
{events: ["brushed teeth","work"],pulpo:false},
{events: ["lettuce","brushed teeth","running","work"],pulpo:false},
{events: ["candy","brushed teeth","work"],pulpo:false},
{events: ["brussel sprouts","brushed teeth","computer","work"],pulpo:false},
{events: ["bread","brushed teeth","weekend"],pulpo:false},
{events: ["cauliflower","brushed teeth","weekend"],pulpo:false},
{events: ["spaghetti","candy","television","work","touched tree"],pulpo:false},
{events: ["carrot","pudding","brushed teeth","work"],pulpo:false},
{events: ["lettuce","brushed teeth","work"],pulpo:false},
{events: ["carrot","ice cream","brushed teeth","cycling","work"],pulpo:false},
{events: ["pizza","brushed teeth","work"],pulpo:false},
{events: ["spaghetti","peanuts","exercise","weekend"],pulpo:true},
{events: ["bread","beer","computer","weekend","touched tree"],pulpo:false},
{events: ["brushed teeth","running","work"],pulpo:false},
{events: ["lettuce","peanuts","brushed teeth","work","touched tree"],pulpo:false},
{events: ["lasagna","brushed teeth","television","work"],pulpo:false},
{events: ["cauliflower","brushed teeth","running","work"],pulpo:false},
{events: ["carrot","brushed teeth","running","work"],pulpo:false},
{events: ["carrot","reading","weekend"],pulpo:false},
{events: ["carrot","peanuts","reading","weekend"],pulpo:true},
{events: ["potatoes","brushed teeth","running","work"],pulpo:false},
{events: ["lasagna","ice cream","work","touched tree"],pulpo:false},
{events: ["cauliflower","peanuts","brushed teeth","cycling","work"],pulpo:false},
{events: ["pizza","brushed teeth","running","work"],pulpo:false},
{events: ["lettuce","brushed teeth","work"],pulpo:false},
{events: ["bread","brushed teeth","television","weekend"],pulpo:false},
{events: ["cauliflower","peanuts","brushed teeth","weekend"],pulpo:false}
]
